version: '3'

services:
  web-app:
    build: ./emcare-web
    environment:
      - KEYCLOACK_SERVER_URL=http://keycloak:8080/auth
      - KEYCLOACK_CLIENT_SECRET=${KEYCLOACK_CLIENT_SECRET}
      - KEYCLOACK_CLIENT_ID=${KEYCLOACK_CLIENT_ID}
      - KEYCLOACK_REALM=emcare
      - KEYCLOACK_USER_NAME=${KEYCLOACK_USER_NAME}
      - KEYCLOACK_PASSWORD=${KEYCLOACK_PASSWORD}
      - KEYCLOAK_ADMIN_USER=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - DB_HOST=postgres-app
      - DB_NAME=webapp
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
      - TWILLO_SSID=${TWILLO_SSID}
      - TWILLO_TOKEN=${TWILLO_TOKEN}
      - TWILLO_SID=${TWILLO_SID}
      - TWILLO_NUMBER=${TWILLO_NUMBER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_USER=${MAIL_USER}
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - IBM_KEY=${IBM_KEY}
    depends_on:
      - postgres-app


  nginx:
    build: 
      context: ./emcare-ui
      args:
       - NG_APP_API_URL="api"
       - NG_APP_KC_URL="${KEYCLOACK_SERVER_URL}"
       - NG_APP_QUESTIONNAIRE_BUILDER_URL="https://emcare.argusoft.com/questionnaireBuilder"
       - NG_APP_SSO_USER="${KEYCLOACK_CLIENT_ID}"
       - NG_APP_SSO_SECRET="${KEYCLOACK_CLIENT_SECRET}"
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      # need to be 1.1 mapping for the reverse proxy port
      - 8080:8080
    depends_on:
      - keycloak
      - web-app

  keycloak:
     image: jboss/keycloak
     restart: on-failure
     environment:
       - PROXY_ADDRESS_FORWARDING=true
       - KEYCLOAK_USER=${KEYCLOAK_ADMIN_USER}
       - KEYCLOAK_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
       - DB_DATABASE=keycloakdb
       - DB_USER=${DB_USER}
       - DB_PASSWORD=${DB_PASSWORD}
       - DB_VENDOR=postgres
       - DB_ADDR=postgres-kc



  postgres-kc:
    image: postgres:10
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: keycloakdb
    volumes:
      - pgdata:/var/lib/postgresql/data
  postgres-app:
    image: postgres:10
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: webapp
    volumes:
      - pgdata-app:/var/lib/postgresql/data
volumes:
  pgdata:
  pgdata-app:
